### PR TITLE
Display parsing errors in grammar compiler

### LINKED ISSUE #4141: grammar-compiler XML parser errors are reported as "source contains no grammar files"
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Trying to run `sudo ./script/add-grammar https://github.com/infosec-intern/textmate-snort`, getting 
```
Registering new submodule: vendor/grammars/textmate-snort
$ git submodule add -f https://github.com/infosec-intern/textmate-snort vendor/grammars/textmate-snort
$ script/grammar-compiler add vendor/grammars/textmate-snort
  > latest: Pulling from linguist/grammar-compiler
  > Digest: sha256:b019869fcf736922e21dd44d2982a0f78ce31b9d24f73f4f758ef1a071c8b4a7
  > Status: Image is up to date for linguist/grammar-compiler:latest
  > source 'vendor/grammars/textmate-snort' contains no grammar files
Command failed. Aborting.
```
Grammar is at https://github.com/infosec-intern/textmate-snort/blob/master/syntaxes/snort.tmLanguage

It sounds like this should have been fixed by https://github.com/github/linguist/pull/4015

### PR DESCRIPTION
**Pull request by pchaigno**
Display parsing errors in grammar compiler. Fixes #4141.

Here's how the error from #4141 would appear:
```
Checking docker is installed and running
$ docker ps
Registering new submodule: vendor/grammars/textmate-snort
$ git submodule add -f https://github.com/infosec-intern/textmate-snort vendor/grammars/textmate-snort
$ script/grammar-compiler add vendor/grammars/textmate-snort
  > The new grammar repository `vendor/grammars/textmate-snort` (from https://github.com/infosec-intern/textmate-snort) contains 1 errors:
  >     - Grammar conversion failed. File `syntaxes/snort.tmLanguage` failed to parse: XML syntax error on line 157: expected element name after <
  >
  > failed to compile the given grammar
Command failed. Aborting.
```

/cc @wesinator 

*Removed template as it doesn't apply.*

### CODE REVIEW

File: tools/grammars/compiler/converter.go [hunk 1]
```diff
@@ -65,6 +65,9 @@ func (conv *Converter) tmpScopes() map[string]bool {
 func (conv *Converter) AddGrammar(source string) error {
 	repo := conv.Load(source)
 	if len(repo.Files) == 0 {
+		if len(repo.Errors) > 0 {
+			return fmt.Errorf("Parsing error in '%s': %s", source, repo.Errors[0])
+		}
```
Comment (lildude) [inline tools/grammars/compiler/converter.go]: This feels a bit odd to me: "We found no grammar files, but hey, here's an error."

I'm mostly AFK this week so don't have time to dig into this deeper myself, but couldn't we check for errors in the first `if`, eg:

```golang
if len(repo.Files) == 0 && len(repo.Errors) == 0 {
	return fmt.Errorf("source '%s' contains no grammar files", source)
}
```

... and only return if we really don't find any files and leave the error reporting for the check slightly further down?

Comment (pchaigno) [reply tools/grammars/compiler/converter.go]: Oh, right! That should work.

I'll update the pull request tonight.

Comment (pchaigno) [reply tools/grammars/compiler/converter.go]: Done.

**Comment by pchaigno** [comment]
@lildude I think this is ready to be merged :smiley:
